Updated
Added function to populate data:
     object.get_data()

Getting an error with the rules though: 

Traceback (most recent call last):
  File "fuzzysystem.py", line 98, in <module>
    crop.update()
  File "fuzzysystem.py", line 82, in update
    self._plant_system.compute()
  File "/usr/local/lib/python2.7/dist-packages/skfuzzy/control/controlsystem.py", line 374, in compute
    CrispValueCalculator(consequent, self).defuzz()
  File "/usr/local/lib/python2.7/dist-packages/skfuzzy/control/controlsystem.py", line 590, in defuzz
    raise ValueError("Crisp output cannot be calculated, likely "
ValueError: Crisp output cannot be calculated, likely because the system is too sparse. Check to make sure this set of input values will activate at least one connected Term in each Antecedent via the current set of Rules.